# Dockerfile.dev
FROM eidos-service.di.unito.it/vitturini/vivit:base

# Copy the entire project directory into the container
COPY . /workspace

# Set the working directory
WORKDIR /workspace

# Set wandb agent as the entrypoint
ENTRYPOINT ["wandb", "agent"]

## Before running the sweep, build and push the image