experiment_name: test_e2e_reg

model_config:
  attention_probs_dropout_prob: 0.0
  freeze: []
  hidden_act: gelu_fast
  hidden_dropout_prob: 0.0
  image_size: ${trainer_config.resize_to}
  num_labels: 1
  num_attention_heads: 12
  num_channels: 1
  num_frames: 32
  num_hidden_layers: 12
  problem_type: regression
  tubelet_size: [2, 16, 16]
  video_size:
    - ${model_config.num_frames}
    - ${model_config.image_size}
    - ${model_config.image_size}
  model_name_or_path: "google/vivit-b-16x2"

trainer_config:
  contrastive_sigma: 0.15
  dataset_folder: fix_apical4
  training_mode: end_to_end_regression
  eval_strategy: epoch
  fp16: true
  kernel_type: gaussian
  learning_rate: 5e-3
  logging_first_step: true
  logging_strategy: epoch
  lr_scheduler_type: constant_with_warmup
  num_train_epochs: 100
  per_device_eval_batch_size: 32
  per_device_train_batch_size: 32
  remove_unused_columns: false
  report_to: wandb
  resize_to: 112
  resume_from_checkpoint: false
  output_dir: ${experiment_name}
  save_strategy: epoch
  warmup_steps: 14
  weight_decay: 1e-3
